Repository VictoriaFC/rotten, pull requests merged in 2022-07, with the labels that each got.

#8 Feature/initial page buildout
  src/CSS/App.css
  src/CSS/MoviePoster.css
  src/CSS/Movies.css
  src/Components/App.js
  src/Components/MoviePoster.js
  src/Components/MoviePreview.js
  src/Components/Movies.js
  src/index.js
Labels: enhancement

#12 Feature/display preview
  src/Components/App.js
  src/Components/MoviePoster.js
  src/Components/MoviePreview.js
  src/Components/Movies.js
Labels: enhancement

#29 Build out Consent component w/Redirect
  src/CSS/Consent.css
  src/Components/App.js
  src/Components/Consent.js
Labels: enhancement

#32 Feature/signup page
  src/CSS/SignUp.css
  src/Components/App.js
  src/Components/Nav.js
  src/Components/Signup.js
Labels: enhancement, iteration 5

#33 Enhancement/create login capability
  package-lock.json
  package.json
  src/Components/App.js
  src/Components/Login.js
  src/Components/Logout.js
  src/Components/Nav.js
  src/Components/Signup.js
Labels: enhancement, iteration 5

#38 Fix title
  public/index.html
Labels: enhancement

#40 Add ability to favorite movie to movie preview. Create post and delete.
  src/CSS/Favorites.css
  src/CSS/MoviePreview.css
  src/Components/App.js
  src/Components/Favorites.js
  src/Components/MoviePreview.js
  src/assets/NotFav.png
  src/assets/favorite.png
Labels: enhancement

#49 Enhancement/consent button nav
  src/CSS/Consent.css
  src/Components/App.js
  src/Components/Consent.js
Labels: bug, enhancement, Refactor, Styling

#53 Refactor/cypress tests
  cypress/e2e/app.spec.cy.js
  src/Components/Consent.js
  src/Components/Nav.js
Labels: Testing, Refactor

#56 update readme with reflection
  README.md
Labels: documentation

#58 delete dead code/spaces
  src/CSS/App.css
  src/CSS/Consent.css
  src/CSS/Favorites.css
  src/CSS/Header.css
  src/CSS/Login.css
  src/CSS/MoviePoster.css
  src/CSS/MoviePreview.css
  src/CSS/Nav.css
  src/CSS/SignUp.css
  src/Components/App.js
  src/Components/Consent.js
  src/Components/Favorites.js
  src/Components/Header.js
  src/Components/MoviePreview.js
  src/Components/Nav.js
Labels: Refactor

#60 Testing/sad path
  cypress/e2e/login.spec.cy.js
  cypress/e2e/signup.spec.cy.js
Labels: Testing

#62 update description in index.html
  public/index.html
Labels: documentation
